# Generated by Django 5.0.6 on 2024-05-21 19:24

import cloudinary.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('color', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=10), size=None)),
                ('stock', models.IntegerField()),
                ('review', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=200), size=None)),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=20), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
