# Generated by Django 5.0.6 on 2024-07-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productmodel_price_alter_saledetailmodel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemodel',
            name='total_gravada',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salemodel',
            name='total_igv',
            field=models.FloatField(default=0.0),
        ),
    ]
