# Generated by Django 5.0.6 on 2024-07-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_salemodel_total_gravada_salemodel_total_igv'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
