# Generated by Django 5.0.6 on 2024-05-21 20:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productmodel_category_alter_productmodel_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=20), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='color',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=10), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='review',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=200), null=True, size=None),
        ),
    ]
