# Generated by Django 5.0.6 on 2024-05-22 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productmodel_category_alter_productmodel_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saledetailmodel',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='saledetailmodel',
            old_name='sale_id',
            new_name='sale',
        ),
        migrations.RenameField(
            model_name='salemodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
