# Generated by Django 5.0.6 on 2024-05-22 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_product_id_saledetailmodel_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saledetailmodel',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='saledetailmodel',
            old_name='sale',
            new_name='sale_id',
        ),
        migrations.RenameField(
            model_name='salemodel',
            old_name='user',
            new_name='user_id',
        ),
    ]
